### ISSUE TITLE
Hotkeys Refactor

### ISSUE THREAD

**Issue by GameOverture** [GameOverture/HarmonyEngine#146]
### Input Refactors
- [x] Ensure all hotkeys and hotkey combinations can be done with only left hand
- [x] WASD Pans camera in main Harmony view
- [x] WASD Scrolls view in Entity Dope Sheet
- [x] WASD Scrolls view in Asset Inspector
- [x] Mouse Wheel Zooms in main Harmony view
- [x] Mouse Wheel Zooms Asset Inspector
- [x] Spacebar is repurposed to be the Play/Pause button for Sprites and Entities
- [x] Ctrl+Tab[+Shift] cycle open item tabs

### Snap Manager
- [x] Refactor Entity Snap Settings to be globally accessible
- [x] Make sure you can snap to Ruler's Guides

### Sprite Updates
- [x] Refactor Transform tool to be used globally (selectable sprite)
- [x] Snap

**Comment by GameOverture** [comment]
Hotkeys refacturd
