### ISSUE TITLE
Rulers and Guides

### ISSUE THREAD

**Issue by GameOverture** [GameOverture/HarmonyEngine#39]
- [x] Create horizontal/vertical rulers over Harmony Widget
- [x] Drag guides from rulers and render guides
- [x] Change mouse cursor while setting guides
    - [x] Be able to update guides (also hover mouse cursor)
- [x] Save guides in meta data of the item
- [x] Have transforms snap to placed guides

**Comment by GameOverture** [comment]
Donezo with [a3b9713](https://github.com/GameOverture/HarmonyEngine/commit/a3b97137c16578141b0dc89db0371b557b130c9e)
